# Given a bank customer, build a neural network-based classifier that can determine whether they will leave or not in the next 6 months.

Dataset Description: The case study is from an open-source dataset from Kaggle. The dataset contains 10,000 sample points with 14 distinct features such as CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance, etc. Link to the Kaggle project: https://www.kaggle.com/barelydedicated/bank-customer-churn-modeling Perform following steps:
1. Read the dataset.
2. Distinguish the feature and target set and divide the data set into training and test sets.
3. Normalize the train and test data. 
4. Initialize and build the model. Identify the points of improvement and implement the same.
5. Print the accuracy score and confusion matrix.

In [ ]:
import pandas as pd
import numpy as np
import  seaborn as sb

In [ ]:
#Read the dataset
df=pd.read_csv("Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

# Distinguish the feature and target set and divide the data set into training and test sets.

In [ ]:
X=df[['CreditScore','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Exited']]
states=pd.get_dummies(df['Geography'],drop_first = True)
gender=pd.get_dummies(df['Gender'],drop_first = True)

In [ ]:
df=pd.concat([X,gender,states],axis=1)

In [ ]:
df.head(5)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Male  Germany  Spain  
0               1        101348.88       1     0        0      0  
1               1        112542.58       0     0        0      1  
2               0        113931.57       1     0        0      0  
3               0         93826.63       0     0        0      0  
4               1         79084.10       0     0        0      1

In [ ]:
X=df.drop(['Exited'],axis=1)
Y=df['Exited']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=2)

# Normalize the train and test data

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [ ]:
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [ ]:
X_train

array([[ 0.40603944, -1.2255974 , -0.69902887, ..., -1.08690612,
        -0.58768841, -0.56877202],
       [-1.05419348,  0.37842889, -0.69902887, ..., -1.08690612,
         1.70158197, -0.56877202],
       [-2.13124471, -0.84817945, -0.69902887, ..., -1.08690612,
        -0.58768841, -0.56877202],
       ...,
       [ 2.06304133, -0.28205252, -0.69902887, ...,  0.92004266,
        -0.58768841, -0.56877202],
       [-1.03348096,  1.41632826, -0.00897076, ...,  0.92004266,
         1.70158197, -0.56877202],
       [ 0.03321401, -1.03688842,  0.68108736, ..., -1.08690612,
        -0.58768841, -0.56877202]])

In [ ]:
X_test

array([[ 0.83723003, -0.07477521,  1.74412033, ..., -1.11753101,
        -0.557843  , -0.58556189],
       [-0.05072348,  0.21871667, -1.0364621 , ..., -1.11753101,
         1.79261907, -0.58556189],
       [-0.32949959,  1.68617608,  0.70140192, ...,  0.89482975,
        -0.557843  , -0.58556189],
       ...,
       [ 0.29000287, -0.27043646, -0.6888893 , ...,  0.89482975,
         1.79261907, -0.58556189],
       [ 0.76495475, -0.17260584,  0.35382912, ...,  0.89482975,
         1.79261907, -0.58556189],
       [ 1.13665622,  0.02305542,  0.35382912, ...,  0.89482975,
        -0.557843  , -0.58556189]])

# Initialize and build the model. Identify the points of improvement and implement the same.

In [ ]:
import keras

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
Classifier = Sequential()
Classifier.add(Dense(150,input_dim=11,activation = 'tanh'))
Classifier.add(Dense(150,activation = 'tanh'))
Classifier.add(Dense(150,activation = 'tanh'))
Classifier.add(Dense(1, activation='sigmoid'))
Classifier.compile(loss='binary_crossentropy', optimizer='adam', metrics = ['accuracy'])
Classifier.fit(X_train,Y_train,epochs=100,batch_size=15)


Epoch 1/100
467/467 [==============================] - 2s 3ms/step - loss: 0.4106 - accuracy: 0.8266
Epoch 2/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3591 - accuracy: 0.8504
Epoch 3/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3525 - accuracy: 0.8553
Epoch 4/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3462 - accuracy: 0.8559
Epoch 5/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3410 - accuracy: 0.8591
Epoch 6/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3413 - accuracy: 0.8603
Epoch 7/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3360 - accuracy: 0.8613
Epoch 8/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3369 - accuracy: 0.8586
Epoch 9/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3291 - accuracy: 0.8639
Epoch 10/100
467/467 [==============================] - 2s 3ms/step - loss: 0.3263 - accura

In [ ]:
Classifier.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 150)               1800      
                                                                 
 dense_5 (Dense)             (None, 150)               22650     
                                                                 
 dense_6 (Dense)             (None, 150)               22650     
                                                                 
 dense_7 (Dense)             (None, 1)                 151       
                                                                 
Total params: 47,251
Trainable params: 47,251
Non-trainable params: 0
_________________________________________________________________


In [ ]:
y_pred =Classifier.predict(X_test)
y_pred[y_pred>0.5]=1
y_pred[y_pred<0.5]=0

94/94 [==============================] - 0s 2ms/step


In [ ]:
y_pred = y_pred.astype(int)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [ ]:
count1=0
count0=0
for i in y_pred:
  if i==1:
    count1+=1
  else:
    count0+=1
print(count1)
print(count0)

510
2490


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
cm=confusion_matrix(Y_test,y_pred)
print(cm)

[[2204  211]
 [ 286  299]]


In [ ]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.91      0.90      2415
           1       0.59      0.51      0.55       585

    accuracy                           0.83      3000
   macro avg       0.74      0.71      0.72      3000
weighted avg       0.83      0.83      0.83      3000

